import 'package:watchlist_app/features/watchlist/dataModel/symbol_model.dart';
import 'package:watchlist_app/features/watchlist/dataModel/watch_list_group_model.dart';

List<WatchListGroupModel> groups = [
  WatchListGroupModel(groupname: "2", symbols: []),
  WatchListGroupModel(groupname: "NIFTY", symbols: []),
  WatchListGroupModel(groupname: "BANKNIFTY", symbols: []),
  WatchListGroupModel(groupname: "SENSEX", symbols: []),
];

List<SymbolModel> mockSymbols = [
  SymbolModel(
      name: "RELIANCE",
      exchange: "NSE",
      price: 2450.75,
      change: 35.50,
      changePercentage: 1.47,
      quantity: 100),
  SymbolModel(
      name: "TCS",
      exchange: "BSE",
      price: 3520.50,
      change: 45.30,
      changePercentage: 1.30,
      quantity: 200),
  SymbolModel(
      name: "INFY",
      exchange: "NSE",
      price: 1585.75,
      change: -10.20,
      changePercentage: -0.64,
      quantity: 150),
  SymbolModel(
      name: "HDFCBANK",
      exchange: "BSE",
      price: 1620.10,
      change: 15.20,
      changePercentage: 0.94,
      quantity: 300),
  SymbolModel(
      name: "ITC",
      exchange: "BSE",
      price: 420.30,
      change: 5.50,
      changePercentage: 1.32,
      quantity: 500),
  SymbolModel(
      name: "WIPRO",
      exchange: "NSE",
      price: 620.15,
      change: -5.15,
      changePercentage: -0.82,
      quantity: 250),
  SymbolModel(
      name: "LT",
      exchange: "NSE",
      price: 2560.40,
      change: 30.40,
      changePercentage: 1.20,
      quantity: 400),
  SymbolModel(
      name: "BAJAJ-AUTO",
      exchange: "BSE",
      price: 3890.20,
      change: -50.75,
      changePercentage: -1.29,
      quantity: 180),
  SymbolModel(
      name: "HCLTECH",
      exchange: "NSE",
      price: 1210.90,
      change: 10.40,
      changePercentage: 0.87,
      quantity: 220),
  SymbolModel(
      name: "MARUTI",
      exchange: "NSE",
      price: 8940.75,
      change: -75.25,
      changePercentage: -0.84,
      quantity: 320),
  SymbolModel(
      name: "ONGC",
      exchange: "BSE",
      price: 178.50,
      change: 3.25,
      changePercentage: 1.85,
      quantity: 600),
  SymbolModel(
      name: "TATASTEEL",
      exchange: "NSE",
      price: 1260.55,
      change: -12.40,
      changePercentage: -0.97,
      quantity: 350),
  SymbolModel(
      name: "COALINDIA",
      exchange: "NSE",
      price: 220.10,
      change: -4.80,
      changePercentage: -2.13,
      quantity: 450),
  SymbolModel(
      name: "SUNPHARMA",
      exchange: "BSE",
      price: 1045.60,
      change: 20.50,
      changePercentage: 1.99,
      quantity: 270),
  SymbolModel(
      name: "NTPC",
      exchange: "NSE",
      price: 135.75,
      change: 2.35,
      changePercentage: 1.76,
      quantity: 800),
  SymbolModel(
      name: "AXISBANK",
      exchange: "NSE",
      price: 975.30,
      change: -5.10,
      changePercentage: -0.52,
      quantity: 500),
  SymbolModel(
      name: "SBIN",
      exchange: "BSE",
      price: 585.45,
      change: 12.00,
      changePercentage: 2.09,
      quantity: 600),
  SymbolModel(
      name: "POWERGRID",
      exchange: "NSE",
      price: 195.65,
      change: 1.75,
      changePercentage: 0.90,
      quantity: 700),
  SymbolModel(
      name: "JSWSTEEL",
      exchange: "BSE",
      price: 810.20,
      change: -8.00,
      changePercentage: -0.98,
      quantity: 250),
  SymbolModel(
      name: "ADANIPORTS",
      exchange: "NSE",
      price: 785.30,
      change: 14.75,
      changePercentage: 1.91,
      quantity: 400),
  SymbolModel(
      name: "BPCL",
      exchange: "NSE",
      price: 465.20,
      change: 6.20,
      changePercentage: 1.35,
      quantity: 300),
  SymbolModel(
      name: "UPL",
      exchange: "BSE",
      price: 710.40,
      change: -9.25,
      changePercentage: -1.29,
      quantity: 350),
  SymbolModel(
      name: "HINDUNILVR",
      exchange: "NSE",
      price: 2325.60,
      change: 30.10,
      changePercentage: 1.31,
      quantity: 220),
  SymbolModel(
      name: "M&M",
      exchange: "NSE",
      price: 1220.90,
      change: 12.50,
      changePercentage: 1.03,
      quantity: 400),
  SymbolModel(
      name: "GAIL",
      exchange: "BSE",
      price: 155.20,
      change: 2.80,
      changePercentage: 1.84,
      quantity: 450),
  SymbolModel(
      name: "DABUR",
      exchange: "NSE",
      price: 530.75,
      change: -4.00,
      changePercentage: -0.75,
      quantity: 200),
];
